# Generated by Django 4.0.3 on 2022-08-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('SDT', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenKH', models.CharField(max_length=50)),
                ('DiaChi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=50)),
                ('DiaChi', models.CharField(max_length=50)),
                ('SDT', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='XeKhach',
            fields=[
                ('BienSoXe', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('GioXuatBen', models.DateTimeField()),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='VeXe',
            fields=[
                ('MaHD', models.AutoField(primary_key=True, serialize=False)),
                ('SDT', models.CharField(max_length=10)),
                ('ChoNgoi', models.CharField(max_length=5)),
                ('NgBan', models.DateField()),
                ('GioXuatBen', models.DateTimeField()),
                ('Giave', models.BinaryField()),
                ('BienSoXe', models.CharField(max_length=20)),
                ('TenKH', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenTk', models.CharField(max_length=20)),
                ('MatKhau', models.CharField(max_length=20)),
                ('SDT', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.khachhang')),
            ],
        ),
    ]
