# Generated by Django 4.0.3 on 2022-08-23 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='khachhang',
            table='KhachHang',
        ),
        migrations.AlterModelTable(
            name='nhanvien',
            table='NhanVien',
        ),
        migrations.AlterModelTable(
            name='taikhoan',
            table='TaiKhoan',
        ),
        migrations.AlterModelTable(
            name='vexe',
            table='VeXe',
        ),
        migrations.AlterModelTable(
            name='xekhach',
            table='XeKhach',
        ),
    ]
